three_star_list = [{'Restaurant Name': 'Kashiwaya',
  'Price Range': '13,000 - 43,000 JPY',
  'Restauarant Website': 'https://jp-kashiwaya.com/senriyama/'},
 {'Restaurant Name': 'HAJIME',
  'Price Range': '40,000 - 54,000 JPY',
  'Restauarant Website': 'http://www.hajime-artistes.com/'},
 {'Restaurant Name': 'Taian',
  'Price Range': '20,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Isshisoden Nakamura',
  'Price Range': '26,000 - 38,000 JPY',
  'Restauarant Website': 'http://www.kyoryori-nakamura.com/'},
 {'Restaurant Name': 'Kikunoi Honten',
  'Price Range': '17,000 - 64,000 JPY',
  'Restauarant Website': 'https://kikunoi.jp/'},
 {'Restaurant Name': 'Gion Sasaki',
  'Price Range': '8,000 - 37,000 JPY',
  'Restauarant Website': 'http://gionsasaki.com/'},
 {'Restaurant Name': 'Mizai',
  'Price Range': '50,000 JPY',
  'Restauarant Website': 'https://mizai.jp/'},
 {'Restaurant Name': 'Hyotei',
  'Price Range': '26,000 - 64,000 JPY',
  'Restauarant Website': 'http://hyotei.co.jp/'},
 {'Restaurant Name': 'Maeda',
  'Price Range': '49,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'The French Laundry',
  'Price Range': '350 - 450 USD',
  'Restauarant Website': 'https://www.thomaskeller.com/tfl'},
 {'Restaurant Name': 'SingleThread',
  'Price Range': '375 USD',
  'Restauarant Website': 'https://www.singlethreadfarms.com/'},
 {'Restaurant Name': 'Manresa',
  'Price Range': '325 USD',
  'Restauarant Website': 'https://www.manresarestaurant.com/'},
 {'Restaurant Name': 'Atelier Crenn',
  'Price Range': '298 USD',
  'Restauarant Website': 'https://www.ateliercrenn.com/'},
 {'Restaurant Name': 'Benu',
  'Price Range': '350 USD',
  'Restauarant Website': 'https://www.benusf.com/'},
 {'Restaurant Name': 'Quince',
  'Price Range': '195 - 298 USD',
  'Restauarant Website': 'https://www.quincerestaurant.com/'},
 {'Restaurant Name': 'Frantzén',
  'Price Range': '3,800 SEK',
  'Restauarant Website': 'https://www.restaurantfrantzen.com/'},
 {'Restaurant Name': 'Maaemo',
  'Price Range': '3,500 NOK',
  'Restauarant Website': 'www.maaemo.no'},
 {'Restaurant Name': 'Geranium',
  'Price Range': '2,800 DKK',
  'Restauarant Website': 'https://www.geranium.dk/'},
 {'Restaurant Name': 'noma',
  'Price Range': '2,800 DKK',
  'Restauarant Website': 'http://www.noma.dk/'},
 {'Restaurant Name': 'Odette',
  'Price Range': '248 - 358 SGD',
  'Restauarant Website': 'https://www.odetterestaurant.com/'},
 {'Restaurant Name': 'Les Amis',
  'Price Range': '155 - 480 SGD',
  'Restauarant Website': 'https://www.lesamis.com.sg/'},
 {'Restaurant Name': 'Zén',
  'Price Range': '450 SGD',
  'Restauarant Website': 'https://www.restaurantzen.com/'},
 {'Restaurant Name': 'Le Palais',
  'Price Range': '2,000 - 5,000 TWD',
  'Restauarant Website': 'https://www.palaisdechinehotel.com/'},
 {'Restaurant Name': 'Eleven Madison Park',
  'Price Range': '125 - 285 USD',
  'Restauarant Website': 'https://www.elevenmadisonpark.com/'},
 {'Restaurant Name': 'Per Se',
  'Price Range': '355 USD',
  'Restauarant Website': 'http://www.perseny.com/'},
 {'Restaurant Name': 'Masa',
  'Price Range': '595 USD',
  'Restauarant Website': 'https://www.masanyc.com/'},
 {'Restaurant Name': 'Le Bernardin',
  'Price Range': '93 - 228 USD',
  'Restauarant Website': 'https://www.le-bernardin.com/'},
 {'Restaurant Name': "Chef's Table at Brooklyn Fare",
  'Price Range': '395 USD',
  'Restauarant Website': 'http://www.brooklynfare.com/'},
 {'Restaurant Name': 'Alinea',
  'Price Range': '210 - 365 USD',
  'Restauarant Website': 'https://www.alinearestaurant.com/'},
 {'Restaurant Name': 'The Inn at Little Washington',
  'Price Range': '238 USD',
  'Restauarant Website': 'https://www.theinnatlittlewashington.com/'},
 {'Restaurant Name': 'Inter Scaldes',
  'Price Range': '140 - 380 EUR',
  'Restauarant Website': 'https://www.interscaldes.eu/'},
 {'Restaurant Name': 'De Librije',
  'Price Range': '190 - 253 EUR',
  'Restauarant Website': 'https://www.librije.com/'},
 {'Restaurant Name': "Victor's Fine Dining by christian bau",
  'Price Range': '175 - 275 EUR',
  'Restauarant Website': 'https://www.victors-fine-dining.de/'},
 {'Restaurant Name': 'Aqua',
  'Price Range': '225 EUR',
  'Restauarant Website': 'www.restaurant-aqua.com'},
 {'Restaurant Name': 'Restaurant Überfahrt Christian Jürgens',
  'Price Range': '259 - 319 EUR',
  'Restauarant Website': 'www.althoffcollection.com'},
 {'Restaurant Name': 'The Table Kevin Fehling',
  'Price Range': '230 EUR',
  'Restauarant Website': 'http://www.the-table-hamburg.de/'},
 {'Restaurant Name': 'Atelier',
  'Price Range': '195 - 255 EUR',
  'Restauarant Website': 'https://www.bayerischerhof.de/'},
 {'Restaurant Name': 'Waldhotel Sonnora',
  'Price Range': '191 - 249 EUR',
  'Restauarant Website': 'www.hotel-sonnora.de'},
 {'Restaurant Name': 'temporaire - Schwarzwaldstube',
  'Price Range': '150 - 245 EUR',
  'Restauarant Website': 'https://www.traube-tonbach.de/'},
 {'Restaurant Name': 'Rutz',
  'Price Range': '198 - 245 EUR',
  'Restauarant Website': 'https://www.rutz-restaurant.de/'},
 {'Restaurant Name': 'Restaurant Bareiss',
  'Price Range': '150 - 305 EUR',
  'Restauarant Website': 'www.bareiss.com'},
 {'Restaurant Name': 'Vendôme',
  'Price Range': '240 - 285 EUR',
  'Restauarant Website': 'www.schlossbensberg.com'},
 {'Restaurant Name': "Restaurant de l'Hôtel de Ville",
  'Price Range': '185 - 390 CHF',
  'Restauarant Website': 'https://www.restaurantcrissier.com/'},
 {'Restaurant Name': 'Cheval Blanc by Peter Knogl',
  'Price Range': '151 - 270 CHF',
  'Restauarant Website': 'https://www.chevalblancbasel.com/'},
 {'Restaurant Name': 'Schloss Schauenstein',
  'Price Range': '190 - 330 CHF',
  'Restauarant Website': 'https://www.schauenstein.ch/'},
 {'Restaurant Name': 'Jade Dragon',
  'Price Range': '400 - 2,000 MOP',
  'Restauarant Website': 'https://www.cityofdreamsmacau.com/'},
 {'Restaurant Name': 'Robuchon au Dôme',
  'Price Range': '988 - 3,500 MOP',
  'Restauarant Website': 'https://www.grandlisboahotels.com/'},
 {'Restaurant Name': 'The Eight',
  'Price Range': '400 - 3,000 MOP',
  'Restauarant Website': 'https://www.grandlisboahotels.com/'},
 {'Restaurant Name': '8 1/2 Otto e Mezzo - Bombana',
  'Price Range': '700 - 2,080 HKD',
  'Restauarant Website': 'https://www.ottoemezzobombana.com/'},
 {'Restaurant Name': "T'ang Court",
  'Price Range': '400 - 1,700 HKD',
  'Restauarant Website': 'https://www.langhamhotels.com/hongkong'},
 {'Restaurant Name': 'Sushi Shikon',
  'Price Range': '2,000 - 3,500 HKD',
  'Restauarant Website': 'https://www.sushi-shikon.com/'},
 {'Restaurant Name': 'Caprice',
  'Price Range': '745 - 2,600 HKD',
  'Restauarant Website': 'www.fourseasons.com/hongkong'},
 {'Restaurant Name': 'Forum',
  'Price Range': '300 - 2,000 HKD',
  'Restauarant Website': 'www.forumrestaurant1977.com'},
 {'Restaurant Name': 'Lung King Heen',
  'Price Range': '500 - 2,980 HKD',
  'Restauarant Website': 'https://www.fourseasons.com/hongkong'},
 {'Restaurant Name': "L'Atelier de Joël Robuchon",
  'Price Range': '680 - 2,600 HKD',
  'Restauarant Website': 'https://www.robuchon.hk/'},
 {'Restaurant Name': 'Restaurant Gordon Ramsay',
  'Price Range': '110 - 195 GBP',
  'Restauarant Website': 'https://www.gordonramsayrestaurants.com/'},
 {'Restaurant Name': 'Fat Duck',
  'Price Range': '325 GBP',
  'Restauarant Website': 'https://www.thefatduck.co.uk/'},
 {'Restaurant Name': 'Hélène Darroze at The Connaught',
  'Price Range': '85 - 185 GBP',
  'Restauarant Website': 'https://www.the-connaught.co.uk/restaurants-bars/helene-darroze-at-the-connaught/'},
 {'Restaurant Name': 'CORE by Clare Smyth',
  'Price Range': '105 - 165 GBP',
  'Restauarant Website': 'https://www.corebyclaresmyth.com/'},
 {'Restaurant Name': 'Sketch (The Lecture Room & Library)',
  'Price Range': '145 - 165 GBP',
  'Restauarant Website': 'https://www.sketch.london/'},
 {'Restaurant Name': 'Waterside Inn',
  'Price Range': '140 - 188 GBP',
  'Restauarant Website': 'www.waterside-inn.co.uk'},
 {'Restaurant Name': 'Alain Ducasse at The Dorchester',
  'Price Range': '70 - 170 GBP',
  'Restauarant Website': 'https://www.alainducasse-dorchester.com/'},
 {'Restaurant Name': "Le Louis XV - Alain Ducasse à l'Hôtel de Paris",
  'Price Range': '180 - 370 EUR',
  'Restauarant Website': 'https://www.ducasse-paris.com/'},
 {'Restaurant Name': 'Assiette Champenoise',
  'Price Range': '145 - 335 EUR',
  'Restauarant Website': 'https://www.assiettechampenoise.com/'},
 {'Restaurant Name': "Les Prés d'Eugénie - Michel Guérard",
  'Price Range': '265 - 295 EUR',
  'Restauarant Website': 'https://www.lespresdeugenie.com/'},
 {'Restaurant Name': 'Georges Blanc',
  'Price Range': '225 - 310 EUR',
  'Restauarant Website': 'https://www.georgesblanc.com/'},
 {'Restaurant Name': "La Vague d'Or - Cheval Blanc St-Tropez",
  'Price Range': '240 - 375 EUR',
  'Restauarant Website': 'https://www.chevalblanc.com/'},
 {'Restaurant Name': 'Mirazur',
  'Price Range': '320 EUR',
  'Restauarant Website': 'https://www.mirazur.fr/'},
 {'Restaurant Name': 'René et Maxime Meilleur',
  'Price Range': '179 - 345 EUR',
  'Restauarant Website': 'https://www.la-bouitte.com/'},
 {'Restaurant Name': 'Alléno Paris au Pavillon Ledoyen',
  'Price Range': '230 - 395 EUR',
  'Restauarant Website': 'https://www.yannick-alleno.com/'},
 {'Restaurant Name': 'Le 1947',
  'Price Range': '270 - 420 EUR',
  'Restauarant Website': 'https://www.chevalblanc.com/courchevel'},
 {'Restaurant Name': 'AM par Alexandre Mazzia',
  'Price Range': '115 - 265 EUR',
  'Restauarant Website': 'http://www.alexandremazzia.com/'},
 {'Restaurant Name': 'Pic',
  'Price Range': '320 EUR',
  'Restauarant Website': 'https://www.anne-sophie-pic.com/'},
 {'Restaurant Name': 'Troisgros - Le Bois sans Feuilles',
  'Price Range': '120 - 550 EUR',
  'Restauarant Website': 'https://www.troisgros.com/'},
 {'Restaurant Name': 'Pierre Gagnaire',
  'Price Range': '98 - 400 EUR',
  'Restauarant Website': 'https://www.pierregagnaire.com/'},
 {'Restaurant Name': 'Le Pré Catelan',
  'Price Range': '140 - 290 EUR',
  'Restauarant Website': 'http://www.precatelanparis.com/'},
 {'Restaurant Name': "L'Ambroisie",
  'Price Range': '230 - 330 EUR',
  'Restauarant Website': 'https://www.ambroisie-paris.com/'},
 {'Restaurant Name': 'Épicure',
  'Price Range': '185 - 467 EUR',
  'Restauarant Website': 'https://www.oetkercollection.com/fr/hotels/le-bristol-paris/'},
 {'Restaurant Name': 'Christophe Bacquié',
  'Price Range': '205 - 325 EUR',
  'Restauarant Website': 'https://www.hotelducastellet.com/'},
 {'Restaurant Name': 'Maison Lameloise',
  'Price Range': '85 - 260 EUR',
  'Restauarant Website': 'https://www.lameloise.fr/'},
 {'Restaurant Name': 'Enrico Bartolini al Mudec',
  'Price Range': '180 - 250 EUR',
  'Restauarant Website': 'https://www.enricobartolini.net/'},
 {'Restaurant Name': 'Mirazur',
  'Price Range': '320 EUR',
  'Restauarant Website': 'https://www.mirazur.fr/'},
 {'Restaurant Name': 'Restaurant Überfahrt Christian Jürgens',
  'Price Range': '259 - 319 EUR',
  'Restauarant Website': 'www.althoffcollection.com'},
 {'Restaurant Name': 'Da Vittorio',
  'Price Range': '100 - 300 EUR',
  'Restauarant Website': 'https://www.davittorio.com/'},
 {'Restaurant Name': 'Dal Pescatore',
  'Price Range': '120 - 250 EUR',
  'Restauarant Website': 'https://www.dalpescatore.com/'},
 {'Restaurant Name': 'St. Hubertus',
  'Price Range': '280 - 310 EUR',
  'Restauarant Website': 'https://www.st-hubertus.it/'},
 {'Restaurant Name': 'Osteria Francescana',
  'Price Range': '270 - 320 EUR',
  'Restauarant Website': 'https://www.osteriafrancescana.it/'},
 {'Restaurant Name': 'Le Calandre',
  'Price Range': '150 - 225 EUR',
  'Restauarant Website': 'https://www.alajmo.it/'},
 {'Restaurant Name': 'Enoteca Pinchiorri',
  'Price Range': '150 - 345 EUR',
  'Restauarant Website': 'http://www.enotecapinchiorri.com/'},
 {'Restaurant Name': 'Amador',
  'Price Range': '35 - 275 EUR',
  'Restauarant Website': 'http://www.restaurant-amador.com/'},
 {'Restaurant Name': 'Uliassi',
  'Price Range': '150 - 200 EUR',
  'Restauarant Website': 'https://www.uliassi.it/'},
 {'Restaurant Name': 'La Pergola',
  'Price Range': '170 - 290 EUR',
  'Restauarant Website': 'https://www.romecavalieri.com/lapergola'},
 {'Restaurant Name': 'Reale',
  'Price Range': '140 - 200 EUR',
  'Restauarant Website': 'https://www.nikoromito.com/reale/'},
 {'Restaurant Name': 'Kohaku',
  'Price Range': '43,000 JPY',
  'Restauarant Website': 'https://kagurazaka-kohaku.jp/'},
 {'Restaurant Name': 'Kagurazaka Ishikawa',
  'Price Range': '43,000 JPY',
  'Restauarant Website': 'http://www.kagurazaka-ishikawa.co.jp/'},
 {'Restaurant Name': 'RyuGin',
  'Price Range': '49,000 JPY',
  'Restauarant Website': 'https://www.nihonryori-ryugin.com/'},
 {'Restaurant Name': "L'OSIER",
  'Price Range': '13,000 - 44,000 JPY',
  'Restauarant Website': 'https://losier.shiseido.co.jp/'},
 {'Restaurant Name': 'Sushi Yoshitake',
  'Price Range': '38,000 JPY',
  'Restauarant Website': 'http://sushi-yoshitake.com/'},
 {'Restaurant Name': 'Azabu Kadowaki',
  'Price Range': '26,000 - 70,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Kanda',
  'Price Range': '37,000 - 43,000 JPY',
  'Restauarant Website': 'http://www.nihonryori-kanda.com/'},
 {'Restaurant Name': 'Martín Berasategui',
  'Price Range': '191 - 290 EUR',
  'Restauarant Website': 'www.martinberasategui.com'},
 {'Restaurant Name': 'Akelaŕe',
  'Price Range': '240 EUR',
  'Restauarant Website': 'www.akelarre.net'},
 {'Restaurant Name': 'Quique Dacosta',
  'Price Range': '210 EUR',
  'Restauarant Website': 'www.quiquedacosta.es'},
 {'Restaurant Name': 'Cenador de Amós',
  'Price Range': '197 - 235 EUR',
  'Restauarant Website': 'www.cenadordeamos.com'},
 {'Restaurant Name': "L'OSIER",
  'Price Range': '13,000 - 44,000 JPY',
  'Restauarant Website': 'https://losier.shiseido.co.jp/'},
 {'Restaurant Name': 'Sazenka',
  'Price Range': '34,000 - 73,000 JPY',
  'Restauarant Website': 'https://sazenka.com/'},
 {'Restaurant Name': 'Kagurazaka Ishikawa',
  'Price Range': '43,000 JPY',
  'Restauarant Website': 'http://www.kagurazaka-ishikawa.co.jp/'},
 {'Restaurant Name': 'Kanda',
  'Price Range': '37,000 - 43,000 JPY',
  'Restauarant Website': 'http://www.nihonryori-kanda.com/'},
 {'Restaurant Name': "L'Effervescence",
  'Price Range': '34,000 JPY',
  'Restauarant Website': 'http://www.leffervescence.jp/'},
 {'Restaurant Name': 'Quintessence',
  'Price Range': '33,000 JPY',
  'Restauarant Website': 'https://www.quintessence.jp/'},
 {'Restaurant Name': 'Azabu Kadowaki',
  'Price Range': '26,000 - 70,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Joël Robuchon',
  'Price Range': '23,000 - 54,000 JPY',
  'Restauarant Website': 'https://www.robuchon.jp/'},
 {'Restaurant Name': 'RyuGin',
  'Price Range': '49,000 JPY',
  'Restauarant Website': 'https://www.nihonryori-ryugin.com/'},
 {'Restaurant Name': 'Sushi Yoshitake',
  'Price Range': '38,000 JPY',
  'Restauarant Website': 'http://sushi-yoshitake.com/'},
 {'Restaurant Name': 'Kohaku',
  'Price Range': '43,000 JPY',
  'Restauarant Website': 'https://kagurazaka-kohaku.jp/'},
 {'Restaurant Name': 'Makimura',
  'Price Range': '27,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Enoteca Pinchiorri',
  'Price Range': '150 - 345 EUR',
  'Restauarant Website': 'http://www.enotecapinchiorri.com/'},
 {'Restaurant Name': 'Dal Pescatore',
  'Price Range': '120 - 250 EUR',
  'Restauarant Website': 'https://www.dalpescatore.com/'},
 {'Restaurant Name': 'Le Calandre',
  'Price Range': '150 - 225 EUR',
  'Restauarant Website': 'https://www.alajmo.it/'},
 {'Restaurant Name': 'Reale',
  'Price Range': '140 - 200 EUR',
  'Restauarant Website': 'https://www.nikoromito.com/reale/'},
 {'Restaurant Name': 'Piazza Duomo',
  'Price Range': '270 - 300 EUR',
  'Restauarant Website': 'https://www.piazzaduomoalba.it/'},
 {'Restaurant Name': 'Osteria Francescana',
  'Price Range': '270 - 320 EUR',
  'Restauarant Website': 'https://www.osteriafrancescana.it/'},
 {'Restaurant Name': 'Enrico Bartolini al Mudec',
  'Price Range': '180 - 250 EUR',
  'Restauarant Website': 'https://www.enricobartolini.net/'},
 {'Restaurant Name': 'St. Hubertus',
  'Price Range': '280 - 310 EUR',
  'Restauarant Website': 'https://www.st-hubertus.it/'},
 {'Restaurant Name': 'Da Vittorio',
  'Price Range': '100 - 300 EUR',
  'Restauarant Website': 'https://www.davittorio.com/'},
 {'Restaurant Name': 'Uliassi',
  'Price Range': '150 - 200 EUR',
  'Restauarant Website': 'https://www.uliassi.it/'},
 {'Restaurant Name': 'La Pergola',
  'Price Range': '170 - 290 EUR',
  'Restauarant Website': 'https://www.romecavalieri.com/lapergola'},
 {'Restaurant Name': 'Gaon',
  'Price Range': '120,000 - 240,000 KRW',
  'Restauarant Website': 'http://gaonkr.com'},
 {'Restaurant Name': 'La Yeon',
  'Price Range': '109,000 - 280,000 KRW',
  'Restauarant Website': 'https://www.shilla.net/seoul'},
 {'Restaurant Name': 'Xin Rong Ji (Xinyuan South Road)',
  'Price Range': '400 - 2,000 CNY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': "King's Joy",
  'Price Range': '500 - 1,399 CNY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Ultraviolet by Paul Pairet',
  'Price Range': '4,000 - 8,888 CNY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Amador',
  'Price Range': '35 - 275 EUR',
  'Restauarant Website': 'http://www.restaurant-amador.com/'}]

  

  