two_star_list = [{'Restaurant Name': 'Oriole',
  'Price Range': '215 USD',
  'Restauarant Website': 'https://www.oriolechicago.com/'},
 {'Restaurant Name': 'Ever',
  'Price Range': '285 USD',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Smyth',
  'Price Range': '225 - 280 USD',
  'Restauarant Website': 'https://www.smythandtheloyalist.com/'},
 {'Restaurant Name': 'Moody Tongue',
  'Price Range': '200 USD',
  'Restauarant Website': 'https://www.moodytongue.com/'},
 {'Restaurant Name': 'Jônt',
  'Price Range': '50 - 305 USD',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'minibar',
  'Price Range': '295 USD',
  'Restauarant Website': 'https://www.minibarbyjoseandres.com/'},
 {'Restaurant Name': 'Pineapple and Pearls',
  'Price Range': '150 - 325 USD',
  'Restauarant Website': 'https://www.pineappleandpearls.com/'},
 {'Restaurant Name': "L'Atelier de Joël Robuchon",
  'Price Range': '103 - 235 USD',
  'Restauarant Website': 'https://latelier-newyork.com/'},
 {'Restaurant Name': 'Jungsik',
  'Price Range': '165 - 235 USD',
  'Restauarant Website': 'https://www.jungsik.com/'},
 {'Restaurant Name': 'Atera',
  'Price Range': '285 USD',
  'Restauarant Website': 'http://www.ateranyc.com/'},
 {'Restaurant Name': 'Jean-Georges',
  'Price Range': '75 - 248 USD',
  'Restauarant Website': 'https://www.jean-georgesrestaurant.com/'},
 {'Restaurant Name': 'Ko',
  'Price Range': '225 USD',
  'Restauarant Website': 'https://www.momofuku.com/'},
 {'Restaurant Name': 'Gabriel Kreuther',
  'Price Range': '90 - 245 USD',
  'Restauarant Website': 'https://www.gknyc.com/'},
 {'Restaurant Name': 'Ichimura at Uchū',
  'Price Range': '300 USD',
  'Restauarant Website': 'https://www.uchu.nyc/'},
 {'Restaurant Name': 'Atomix',
  'Price Range': '205 USD',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'The Modern',
  'Price Range': '138 - 188 USD',
  'Restauarant Website': 'https://www.themodernnyc.com/'},
 {'Restaurant Name': 'Aquavit',
  'Price Range': '58 - 155 USD',
  'Restauarant Website': 'https://www.aquavit.org/'},
 {'Restaurant Name': 'Daniel',
  'Price Range': '158 - 250 USD',
  'Restauarant Website': 'https://www.danielnyc.com/'},
 {'Restaurant Name': 'Aska',
  'Price Range': '195 - 295 USD',
  'Restauarant Website': 'https://www.askanyc.com/'},
 {'Restaurant Name': 'Blanca',
  'Price Range': '198 USD',
  'Restauarant Website': 'https://www.blancanyc.com/'},
 {'Restaurant Name': 'Kikunoi Roan',
  'Price Range': '9,000 - 32,000 JPY',
  'Restauarant Website': 'https://kikunoi.jp/'},
 {'Restaurant Name': 'Sumibi Kappo Ifuki',
  'Price Range': '24,000 - 35,000 JPY',
  'Restauarant Website': 'https://gion-ifuki.com/'},
 {'Restaurant Name': 'Shimmonzen Yonemura',
  'Price Range': '10,000 - 21,000 JPY',
  'Restauarant Website': 'https://r-yonemura.jp/'},
 {'Restaurant Name': 'Miyamaso',
  'Price Range': '19,000 - 32,000 JPY',
  'Restauarant Website': 'http://miyamasou.jp/'},
 {'Restaurant Name': 'Sojiki Nakahigashi',
  'Price Range': '9,000 - 26,000 JPY',
  'Restauarant Website': 'https://www.soujiki-nakahigashi.co.jp/'},
 {'Restaurant Name': 'Otagi',
  'Price Range': '22,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Kyotenjin Noguchi',
  'Price Range': '30,000 - 35,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Wagokoro Izumi',
  'Price Range': '7,000 - 29,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Gion Owatari',
  'Price Range': '32,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Oryori Mitsuyasu',
  'Price Range': '20,000 JPY',
  'Restauarant Website': 'http://kyoto-mitsuyasu.com/'},
 {'Restaurant Name': 'Twins Garden',
  'Price Range': '2,500 - 15,000 RUB',
  'Restauarant Website': 'http://twinsgarden.ru/'},
 {'Restaurant Name': "ARTEST - Chef's Table",
  'Price Range': '15,000 - 20,000 RUB',
  'Restauarant Website': 'https://artest.rest/'},
 {'Restaurant Name': 'Harbor House',
  'Price Range': '180 USD',
  'Restauarant Website': 'https://www.theharborhouseinn.com/'},
 {'Restaurant Name': 'Vespertine',
  'Price Range': '295 USD',
  'Restauarant Website': 'www.vespertine.la'},
 {'Restaurant Name': 'Providence',
  'Price Range': '225 - 475 USD',
  'Restauarant Website': 'https://www.providencela.com/'},
 {'Restaurant Name': 'Sushi Ginza Onodera',
  'Price Range': '300 USD',
  'Restauarant Website': 'https://www.onodera-group.com/'},
 {'Restaurant Name': 'Addison',
  'Price Range': '175 - 275 USD',
  'Restauarant Website': 'https://www.addisondelmar.com/'},
 {'Restaurant Name': 'Commis',
  'Price Range': '189 USD',
  'Restauarant Website': 'www.commisrestaurant.com'},
 {'Restaurant Name': 'Mélisse',
  'Price Range': '295 USD',
  'Restauarant Website': 'https://www.citrinandmelisse.com/'},
 {'Restaurant Name': 'Hayato',
  'Price Range': '260 USD',
  'Restauarant Website': 'https://www.hayatorestaurant.com/'},
 {'Restaurant Name': 'Patrick Guilbaud',
  'Price Range': '65 - 205 EUR',
  'Restauarant Website': 'https://www.restaurantpatrickguilbaud.ie/'},
 {'Restaurant Name': 'Andrew Fairlie at Gleneagles',
  'Price Range': '115 - 155 GBP',
  'Restauarant Website': 'https://www.andrewfairlie.co.uk/'},
 {'Restaurant Name': "L'Enclume",
  'Price Range': '79 - 175 GBP',
  'Restauarant Website': 'https://www.lenclume.co.uk/'},
 {'Restaurant Name': 'Moor Hall',
  'Price Range': '95 - 195 GBP',
  'Restauarant Website': 'https://www.moorhall.com/'},
 {'Restaurant Name': 'Raby Hunt',
  'Price Range': '230 - 300 GBP',
  'Restauarant Website': 'https://www.rabyhuntrestaurant.co.uk/'},
 {'Restaurant Name': "Il Gallo d'Oro",
  'Price Range': '130 - 200 EUR',
  'Restauarant Website': 'www.ilgallodoro.com'},
 {'Restaurant Name': 'Restaurant Sat Bains',
  'Price Range': '120 - 155 GBP',
  'Restauarant Website': 'https://www.restaurantsatbains.com/'},
 {'Restaurant Name': 'The Dining Room',
  'Price Range': '145 GBP',
  'Restauarant Website': 'https://www.whatleymanor.com/'},
 {'Restaurant Name': 'Culler de Pau',
  'Price Range': '95 - 150 EUR',
  'Restauarant Website': 'www.cullerdepau.com'},
 {'Restaurant Name': "L'Auberge des Glazicks",
  'Price Range': '70 - 180 EUR',
  'Restauarant Website': 'https://www.aubergedesglazick.com/'},
 {'Restaurant Name': "Le Manoir aux Quat' Saisons, a Belmond Hotel",
  'Price Range': '136 - 194 GBP',
  'Restauarant Website': 'https://www.belmond.com/'},
 {'Restaurant Name': 'RE-NAA',
  'Price Range': '2,400 NOK',
  'Restauarant Website': 'https://www.restaurantrenaa.no/'},
 {'Restaurant Name': 'Hand and Flowers',
  'Price Range': '40 - 115 GBP',
  'Restauarant Website': 'https://www.thehandandflowers.co.uk/'},
 {'Restaurant Name': 'Casa de Chá da Boa Nova',
  'Price Range': '70 - 195 EUR',
  'Restauarant Website': 'www.casadechadaboanova.pt'},
 {'Restaurant Name': 'The Yeatman',
  'Price Range': '180 EUR',
  'Restauarant Website': 'www.the-yeatman-hotel.com'},
 {'Restaurant Name': 'Midsummer House',
  'Price Range': '115 - 230 GBP',
  'Restauarant Website': 'www.midsummerhouse.co.uk/'},
 {'Restaurant Name': 'Le Gavroche',
  'Price Range': '85 - 178 GBP',
  'Restauarant Website': 'https://www.le-gavroche.co.uk/'},
 {'Restaurant Name': 'Claude Bosi at Bibendum',
  'Price Range': '105 - 175 GBP',
  'Restauarant Website': 'https://www.claudebosi.com/'},
 {'Restaurant Name': 'Dinner by Heston Blumenthal',
  'Price Range': '87 - 106 GBP',
  'Restauarant Website': 'https://www.dinnerbyheston.com/'},
 {'Restaurant Name': 'Kitchen Table',
  'Price Range': '150 - 195 GBP',
  'Restauarant Website': 'https://www.kitchentablelondon.co.uk/'},
 {'Restaurant Name': 'a|o|c',
  'Price Range': '2,500 DKK',
  'Restauarant Website': 'https://www.aoc.dk/'},
 {'Restaurant Name': 'Jordnær',
  'Price Range': '2,700 DKK',
  'Restauarant Website': 'www.restaurantjordnaer.dk/'},
 {'Restaurant Name': 'Kong Hans Kælder',
  'Price Range': '1,700 DKK',
  'Restauarant Website': 'https://www.konghans.dk/'},
 {'Restaurant Name': 'Alchemist',
  'Price Range': '3,500 DKK',
  'Restauarant Website': 'https://www.alchemist.dk/'},
 {'Restaurant Name': 'Shoukouwa',
  'Price Range': '320 - 650 SGD',
  'Restauarant Website': 'https://www.shoukouwa.com.sg/'},
 {'Restaurant Name': 'Shisen Hanten',
  'Price Range': '50 - 150 SGD',
  'Restauarant Website': 'https://www.shisenhanten.com.sg/'},
 {'Restaurant Name': 'Saint Pierre',
  'Price Range': '158 - 388 SGD',
  'Restauarant Website': 'https://www.saintpierre.com.sg/'},
 {'Restaurant Name': 'Waku Ghin',
  'Price Range': '550 - 700 SGD',
  'Restauarant Website': 'https://www.marinabaysands.com/'},
 {'Restaurant Name': 'Jaan by Kirk Westaway',
  'Price Range': '118 - 288 SGD',
  'Restauarant Website': 'https://www.jaan.com.sg/'},
 {'Restaurant Name': 'Shoun Ryugin',
  'Price Range': '4,500 - 6,500 TWD',
  'Restauarant Website': 'https://www.nihonryori-ryugin.com.tw/'},
 {'Restaurant Name': 'Logy',
  'Price Range': '3,750 TWD',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'JL Studio',
  'Price Range': '3,800 TWD',
  'Restauarant Website': 'https://jlstudiotw.com/'},
 {'Restaurant Name': 'Sushi Amamoto',
  'Price Range': '3,000 - 5,000 TWD',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': "L'Atelier de Joël Robuchon",
  'Price Range': '1,580 - 6,880 TWD',
  'Restauarant Website': 'https://www.robuchon.com.tw/'},
 {'Restaurant Name': 'The Guest House',
  'Price Range': '1,200 - 4,280 TWD',
  'Restauarant Website': 'https://www.sheratongrandtaipei.com/'},
 {'Restaurant Name': 'Taïrroir',
  'Price Range': '2,180 - 4,680 TWD',
  'Restauarant Website': 'https://www.tairroir.com/'},
 {'Restaurant Name': 'Raw',
  'Price Range': '1,850 - 3,500 TWD',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'The Modern',
  'Price Range': '138 - 188 USD',
  'Restauarant Website': 'https://www.themodernnyc.com/'},
 {'Restaurant Name': 'Blue Hill at Stone Barns',
  'Price Range': '195 - 278 USD',
  'Restauarant Website': 'http://www.bluehillfarm.com/'},
 {'Restaurant Name': 'Ko',
  'Price Range': '225 USD',
  'Restauarant Website': 'https://www.momofuku.com/'},
 {'Restaurant Name': 'Vila Joya',
  'Price Range': '110 - 195 EUR',
  'Restauarant Website': 'www.vilajoya.com/'},
 {'Restaurant Name': 'Boury',
  'Price Range': '80 - 160 EUR',
  'Restauarant Website': 'https://www.restaurantboury.be/'},
 {'Restaurant Name': 'Atrio',
  'Price Range': '185 EUR',
  'Restauarant Website': 'www.restauranteatrio.com'},
 {'Restaurant Name': 'De Kromme Watergang',
  'Price Range': '62 - 225 EUR',
  'Restauarant Website': 'https://www.krommewatergang.nl/'},
 {'Restaurant Name': 'La Durée',
  'Price Range': '65 - 232 EUR',
  'Restauarant Website': 'https://www.laduree.be/'},
 {'Restaurant Name': 'De Bokkedoorns',
  'Price Range': '69 - 147 EUR',
  'Restauarant Website': 'https://www.bokkedoorns.nl/'},
 {'Restaurant Name': 'Castor',
  'Price Range': '45 - 120 EUR',
  'Restauarant Website': 'https://www.cas-tor.be/'},
 {'Restaurant Name': 'Henne Kirkeby Kro',
  'Price Range': '650 - 1,495 DKK',
  'Restauarant Website': 'https://www.hennekirkebykro.dk/'},
 {'Restaurant Name': 'FG - François Geurds',
  'Price Range': '55 - 210 EUR',
  'Restauarant Website': 'https://www.fgrestaurant.nl/'},
 {'Restaurant Name': 'Spectrum',
  'Price Range': '95 - 180 EUR',
  'Restauarant Website': 'https://www.restaurantspectrum.com/'},
 {'Restaurant Name': 'Restaurant 212',
  'Price Range': '74 - 158 EUR',
  'Restauarant Website': 'https://www.restaurant-212.com/'},
 {'Restaurant Name': 'Aan de Poel',
  'Price Range': '48 - 140 EUR',
  'Restauarant Website': 'https://www.aandepoel.nl/'},
 {'Restaurant Name': 'Ciel Bleu',
  'Price Range': '195 - 225 EUR',
  'Restauarant Website': 'https://www.okura.nl/'},
 {'Restaurant Name': 'Parkheuvel',
  'Price Range': '44 - 165 EUR',
  'Restauarant Website': 'https://www.parkheuvel.nl/'},
 {'Restaurant Name': 'Fred',
  'Price Range': '59 - 169 EUR',
  'Restauarant Website': 'https://www.restaurantfred.nl/'},
 {'Restaurant Name': 'Vrijmoed',
  'Price Range': '69 - 198 EUR',
  'Restauarant Website': 'https://www.vrijmoed.be/'},
 {'Restaurant Name': 'Château du Mylord',
  'Price Range': '95 - 270 EUR',
  'Restauarant Website': 'https://www.mylord.be/'},
 {'Restaurant Name': 'The Jane',
  'Price Range': '215 EUR',
  'Restauarant Website': 'https://www.thejaneantwerp.com/'},
 {'Restaurant Name': 'Maison Rostang',
  'Price Range': '90 - 203 EUR',
  'Restauarant Website': 'https://www.maisonrostang.com/'},
 {'Restaurant Name': 'Le Taillevent',
  'Price Range': '90 - 245 EUR',
  'Restauarant Website': 'https://www.letaillevent.com/'},
 {'Restaurant Name': 'La Scène',
  'Price Range': '75 - 250 EUR',
  'Restauarant Website': 'https://www.la-scene.paris/'},
 {'Restaurant Name': 'Le Clarence',
  'Price Range': '90 - 320 EUR',
  'Restauarant Website': 'https://www.le-clarence.paris/'},
 {'Restaurant Name': 'Le Gabriel',
  'Price Range': '75 - 195 EUR',
  'Restauarant Website': 'https://www.lareserve-paris.com/'},
 {'Restaurant Name': 'David Toutain',
  'Price Range': '100 - 250 EUR',
  'Restauarant Website': 'https://www.davidtoutain.com/'},
 {'Restaurant Name': 'Le Grand Restaurant - Jean-François Piège',
  'Price Range': '120 - 290 EUR',
  'Restauarant Website': 'http://www.jeanfrancoispiege.com/'},
 {'Restaurant Name': "L'Abysse au Pavillon Ledoyen",
  'Price Range': '98 - 280 EUR',
  'Restauarant Website': 'https://www.yannick-alleno.com/'},
 {'Restaurant Name': 'Sur Mesure par Thierry Marx',
  'Price Range': '85 - 195 EUR',
  'Restauarant Website': 'https://www.mandarinoriental.fr/paris'},
 {'Restaurant Name': 'Le Meurice Alain Ducasse',
  'Price Range': '250 - 320 EUR',
  'Restauarant Website': 'https://www.alainducasse-meurice.com/fr'},
 {'Restaurant Name': 'Marsan par Hélène Darroze',
  'Price Range': '75 - 225 EUR',
  'Restauarant Website': 'https://www.helenedarroze.com/'},
 {'Restaurant Name': 'Les Hauts de Loire',
  'Price Range': '89 - 175 EUR',
  'Restauarant Website': 'https://www.hautsdeloire.com/'},
 {'Restaurant Name': 'Pastorale',
  'Price Range': '65 - 195 EUR',
  'Restauarant Website': 'https://www.depastorale.be/'},
 {'Restaurant Name': "d'Eugénie à Emilie",
  'Price Range': '85 - 200 EUR',
  'Restauarant Website': 'http://www.fernez.com/deugenie-a-emilie'},
 {'Restaurant Name': "'t Nonnetje",
  'Price Range': '50 - 150 EUR',
  'Restauarant Website': 'https://www.hetnonnetje.nl/'},
 {'Restaurant Name': 'De Lindenhof',
  'Price Range': '85 - 175 EUR',
  'Restauarant Website': 'https://www.restaurantdelindenhof.nl/'},
 {'Restaurant Name': 'Nuance',
  'Price Range': '75 - 215 EUR',
  'Restauarant Website': 'https://www.resto-nuance.be/'},
 {'Restaurant Name': 'Le Skiff Club',
  'Price Range': '140 - 160 EUR',
  'Restauarant Website': 'https://www.haaitza.com/'},
 {'Restaurant Name': "Söl'ring Hof",
  'Price Range': '214 - 284 EUR',
  'Restauarant Website': 'https://www.soelring-hof.de/'},
 {'Restaurant Name': 'La Paix',
  'Price Range': '105 - 235 EUR',
  'Restauarant Website': 'https://www.lapaix.eu/'},
 {'Restaurant Name': 'Comme chez Soi',
  'Price Range': '69 - 355 EUR',
  'Restauarant Website': 'https://www.commechezsoi.be/'},
 {'Restaurant Name': "La Maison d'à Côté",
  'Price Range': '88 - 178 EUR',
  'Restauarant Website': 'https://www.lamaisondacote.fr/'},
 {'Restaurant Name': 'Falco',
  'Price Range': '95 - 262 EUR',
  'Restauarant Website': 'https://www.falco-leipzig.de/'},
 {'Restaurant Name': 'Hirschen',
  'Price Range': '98 - 270 EUR',
  'Restauarant Website': 'https://www.douce-steiner.de/'},
 {'Restaurant Name': 'EssZimmer',
  'Price Range': '180 - 275 EUR',
  'Restauarant Website': 'https://www.feinkost-kaefer.de/esszimmer-muenchen'},
 {'Restaurant Name': 'Gustav',
  'Price Range': '120 - 165 EUR',
  'Restauarant Website': 'www.restaurant-gustav.de'},
 {'Restaurant Name': "Luce d'Oro",
  'Price Range': '189 - 229 EUR',
  'Restauarant Website': 'www.schloss-elmau.de'},
 {'Restaurant Name': 'Courtier',
  'Price Range': '159 - 215 EUR',
  'Restauarant Website': 'https://www.weissenhaus.de/'},
 {'Restaurant Name': 'Steinheuers Restaurant Zur Alten Post',
  'Price Range': '120 - 195 EUR',
  'Restauarant Website': 'https://www.steinheuers.de/'},
 {'Restaurant Name': 'CODA Dessert Dining',
  'Price Range': '93 - 158 EUR',
  'Restauarant Website': 'https://www.coda-berlin.com/'},
 {'Restaurant Name': 'bianc',
  'Price Range': '190 EUR',
  'Restauarant Website': 'http://www.bianc.de/'},
 {'Restaurant Name': 'Le Cerf',
  'Price Range': '75 - 174 EUR',
  'Restauarant Website': 'https://www.schlosshotel-friedrichsruhe.de/'},
 {'Restaurant Name': 'Meierei Dirk Luther',
  'Price Range': '178 - 198 EUR',
  'Restauarant Website': 'www.alter-meierhof.de'},
 {'Restaurant Name': 'Tim Raue',
  'Price Range': '88 - 248 EUR',
  'Restauarant Website': 'https://www.tim-raue.com/'},
 {'Restaurant Name': "Söl'ring Hof",
  'Price Range': '214 - 284 EUR',
  'Restauarant Website': 'https://www.soelring-hof.de/'},
 {'Restaurant Name': 'GästeHaus Klaus Erfort',
  'Price Range': '105 - 225 EUR',
  'Restauarant Website': 'https://www.gaestehaus-erfort.de/'},
 {'Restaurant Name': 'Ophelia',
  'Price Range': '190 - 240 EUR',
  'Restauarant Website': 'https://www.restaurant-ophelia.de/'},
 {'Restaurant Name': "Obendorfer's Eisvogel",
  'Price Range': '142 - 190 EUR',
  'Restauarant Website': 'https://www.landhotel-birkenhof.de/'},
 {'Restaurant Name': 'OPUS V',
  'Price Range': '99 - 195 EUR',
  'Restauarant Website': 'https://www.restaurant-opus-v.de/'},
 {'Restaurant Name': 'ammolite - The Lighthouse Restaurant',
  'Price Range': '119 - 169 EUR',
  'Restauarant Website': 'https://www.ammolite-restaurant.de/'},
 {'Restaurant Name': 'Les Deux',
  'Price Range': '185 EUR',
  'Restauarant Website': 'www.lesdeux-muc.de'},
 {'Restaurant Name': 'AUGUST',
  'Price Range': '179 - 210 EUR',
  'Restauarant Website': 'https://www.restaurantaugust.de/'},
 {'Restaurant Name': 'Meierei Dirk Luther',
  'Price Range': '178 - 198 EUR',
  'Restauarant Website': 'www.alter-meierhof.de'},
 {'Restaurant Name': 'Racine',
  'Price Range': '70 - 195 EUR',
  'Restauarant Website': 'https://www.racine.re/'},
 {'Restaurant Name': 'El Molino de Urdániz',
  'Price Range': '120 - 140 EUR',
  'Restauarant Website': 'www.elmolinourdaniz.com'},
 {'Restaurant Name': 'Le Parc Les Crayères',
  'Price Range': '75 - 295 EUR',
  'Restauarant Website': 'www.lescrayeres.com'},
 {'Restaurant Name': 'Ralf Berendsen',
  'Price Range': '95 - 225 EUR',
  'Restauarant Website': 'https://www.restaurantlasource.be/'},
 {'Restaurant Name': 'Sabero',
  'Price Range': '90 - 139 EUR',
  'Restauarant Website': 'http://www.restaurant-sabero.nl/'},
 {'Restaurant Name': 'Brut172',
  'Price Range': '90 - 185 EUR',
  'Restauarant Website': 'https://www.brut172.com/'},
 {'Restaurant Name': 'La Table de Maxime',
  'Price Range': '50 - 109 EUR',
  'Restauarant Website': 'https://www.maximecollard.be/'},
 {'Restaurant Name': 'La Côte Saint-Jacques',
  'Price Range': '85 - 238 EUR',
  'Restauarant Website': 'https://www.cotesaintjacques.com/'},
 {'Restaurant Name': 'Rosin',
  'Price Range': '99 - 159 EUR',
  'Restauarant Website': 'https://www.frankrosin.de/'},
 {'Restaurant Name': 'Noor',
  'Price Range': '95 - 190 EUR',
  'Restauarant Website': 'www.noorrestaurant.es'},
 {'Restaurant Name': 'Le Moissonnier',
  'Price Range': '90 - 165 EUR',
  'Restauarant Website': 'www.lemoissonnier.de'},
 {'Restaurant Name': 'Ox & Klee',
  'Price Range': '230 EUR',
  'Restauarant Website': 'https://www.oxundklee.de/'},
 {'Restaurant Name': 'Courtier',
  'Price Range': '159 - 215 EUR',
  'Restauarant Website': 'https://www.weissenhaus.de/'},
 {'Restaurant Name': 'Haerlin',
  'Price Range': '190 - 250 EUR',
  'Restauarant Website': 'https://www.restaurant-haerlin.de/'},
 {'Restaurant Name': 'bianc',
  'Price Range': '190 EUR',
  'Restauarant Website': 'http://www.bianc.de/'},
 {'Restaurant Name': 'Jordnær',
  'Price Range': '2,700 DKK',
  'Restauarant Website': 'www.restaurantjordnaer.dk/'},
 {'Restaurant Name': 'Bardal',
  'Price Range': '150 - 170 EUR',
  'Restauarant Website': 'www.restaurantebardal.com'},
 {'Restaurant Name': 'a|o|c',
  'Price Range': '2,500 DKK',
  'Restauarant Website': 'https://www.aoc.dk/'},
 {'Restaurant Name': 'Kong Hans Kælder',
  'Price Range': '1,700 DKK',
  'Restauarant Website': 'https://www.konghans.dk/'},
 {'Restaurant Name': "Cà d'Oro",
  'Price Range': '140 - 190 CHF',
  'Restauarant Website': 'https://www.kempinski.com/stmoritz'},
 {'Restaurant Name': 'Ecco',
  'Price Range': '185 - 240 CHF',
  'Restauarant Website': 'https://www.giardino-ascona.ch/'},
 {'Restaurant Name': 'Anne-Sophie Pic',
  'Price Range': '207 - 395 CHF',
  'Restauarant Website': 'https://www.brp.ch/'},
 {'Restaurant Name': 'Taverne zum Schäfli',
  'Price Range': '89 - 220 CHF',
  'Restauarant Website': 'https://www.schaefli-wigoltingen.ch/'},
 {'Restaurant Name': 'Ecco St. Moritz',
  'Price Range': '215 - 270 CHF',
  'Restauarant Website': 'https://www.giardinohotels.ch/'},
 {'Restaurant Name': 'Einstein Gourmet',
  'Price Range': '165 - 215 CHF',
  'Restauarant Website': 'https://www.einstein.ch/'},
 {'Restaurant Name': '7132 Silver',
  'Price Range': '275 CHF',
  'Restauarant Website': 'https://www.7132silver.com/'},
 {'Restaurant Name': 'Domaine de Châteauvieux',
  'Price Range': '98 - 320 CHF',
  'Restauarant Website': 'https://www.chateauvieux.ch/'},
 {'Restaurant Name': 'The Restaurant',
  'Price Range': '112 - 298 CHF',
  'Restauarant Website': 'https://www.thedoldergrand.com/'},
 {'Restaurant Name': 'Gasthaus Zur Fernsicht - Incantare',
  'Price Range': '169 - 230 CHF',
  'Restauarant Website': 'https://www.fernsicht-heiden.ch/'},
 {'Restaurant Name': 'Magdalena',
  'Price Range': '59 - 135 CHF',
  'Restauarant Website': 'https://www.restaurant-magdalena.ch/'},
 {'Restaurant Name': 'Memories',
  'Price Range': '195 - 330 CHF',
  'Restauarant Website': 'https://www.memories.ch/'},
 {'Restaurant Name': 'IGNIV by Andreas Caminada',
  'Price Range': '195 - 245 CHF',
  'Restauarant Website': 'https://www.badruttspalace.com/'},
 {'Restaurant Name': 'Widder Restaurant',
  'Price Range': '145 - 260 CHF',
  'Restauarant Website': 'https://www.widderhotel.com/'},
 {'Restaurant Name': 'Adelboden',
  'Price Range': '148 - 195 CHF',
  'Restauarant Website': 'https://www.wiget-adelboden.ch/'},
 {'Restaurant Name': 'IGNIV by Andreas Caminada',
  'Price Range': '158 - 248 CHF',
  'Restauarant Website': 'https://www.igniv.com/'},
 {'Restaurant Name': 'Pavillon',
  'Price Range': '162 - 275 CHF',
  'Restauarant Website': 'https://www.aupavillon.ch/'},
 {'Restaurant Name': 'Sens',
  'Price Range': '145 - 195 CHF',
  'Restauarant Website': 'https://www.vitznauerhof.ch/'},
 {'Restaurant Name': "RICO'S",
  'Price Range': '66 - 260 CHF',
  'Restauarant Website': 'https://www.ricozandonella.ch/'},
 {'Restaurant Name': 'Sichuan Moon',
  'Price Range': '1,688 - 3,268 MOP',
  'Restauarant Website': 'www.wynnpalace.com'},
 {'Restaurant Name': 'Serge Vieira',
  'Price Range': '95 - 165 EUR',
  'Restauarant Website': 'https://www.sergevieira.com/'},
 {'Restaurant Name': 'Bras',
  'Price Range': '170 - 245 EUR',
  'Restauarant Website': 'https://www.bras.fr/'},
 {'Restaurant Name': 'Au 14 Février',
  'Price Range': '87 - 125 EUR',
  'Restauarant Website': 'https://www.sa-au14fevrier.com/'},
 {'Restaurant Name': 'Villa René Lalique',
  'Price Range': '80 - 205 EUR',
  'Restauarant Website': 'https://www.villarenelalique.com/'},
 {'Restaurant Name': 'Lafleur',
  'Price Range': '195 - 215 EUR',
  'Restauarant Website': 'https://www.restaurant-lafleur.de/'},
 {'Restaurant Name': 'Gustav',
  'Price Range': '120 - 165 EUR',
  'Restauarant Website': 'www.restaurant-gustav.de'},
 {'Restaurant Name': 'Auberge du Cheval Blanc',
  'Price Range': '82 - 135 EUR',
  'Restauarant Website': 'https://www.au-cheval-blanc.fr/'},
 {'Restaurant Name': 'Maison Jeunet',
  'Price Range': '65 - 155 EUR',
  'Restauarant Website': 'https://www.maison-jeunet.com/'},
 {'Restaurant Name': 'La Merise',
  'Price Range': '55 - 135 EUR',
  'Restauarant Website': 'https://www.lamerise.alsace/'},
 {'Restaurant Name': 'La Table de Franck Putelat',
  'Price Range': '75 - 230 EUR',
  'Restauarant Website': 'https://www.franck-putelat.com/'},
 {'Restaurant Name': 'Paul Bocuse',
  'Price Range': '185 - 285 EUR',
  'Restauarant Website': 'https://www.bocuse.fr/'},
 {'Restaurant Name': 'OPUS V',
  'Price Range': '99 - 195 EUR',
  'Restauarant Website': 'https://www.restaurant-opus-v.de/'},
 {'Restaurant Name': 'Mère Brazier',
  'Price Range': '75 - 190 EUR',
  'Restauarant Website': 'https://www.lamerebrazier.fr/'},
 {'Restaurant Name': 'Takao Takano',
  'Price Range': '50 - 150 EUR',
  'Restauarant Website': 'https://www.takaotakano.com/'},
 {'Restaurant Name': 'Le Neuvième Art',
  'Price Range': '105 - 175 EUR',
  'Restauarant Website': 'https://www.leneuviemeart.com/'},
 {'Restaurant Name': 'La Fourchette des Ducs',
  'Price Range': '140 - 210 EUR',
  'Restauarant Website': 'http://www.lafourchettedesducs.com/'},
 {'Restaurant Name': "La Table d'Olivier Nasti",
  'Price Range': '165 - 240 EUR',
  'Restauarant Website': 'https://www.lechambard.fr/'},
 {'Restaurant Name': 'Maralba',
  'Price Range': '65 - 99 EUR',
  'Restauarant Website': 'www.maralbarestaurante.es'},
 {'Restaurant Name': "Auberge de l'Ill",
  'Price Range': '110 - 260 EUR',
  'Restauarant Website': 'https://www.auberge-de-l-ill.com/'},
 {'Restaurant Name': 'La Pyramide - Patrick Henriroux',
  'Price Range': '79 - 204 EUR',
  'Restauarant Website': 'https://www.lapyramide.com/'},
 {'Restaurant Name': 'The Dining Room',
  'Price Range': '145 GBP',
  'Restauarant Website': 'https://www.whatleymanor.com/'},
 {'Restaurant Name': 'La Dame de Pic',
  'Price Range': '45 - 160 GBP',
  'Restauarant Website': 'https://www.ladamedepiclondon.co.uk/'},
 {'Restaurant Name': "L'Enclume",
  'Price Range': '79 - 175 GBP',
  'Restauarant Website': 'https://www.lenclume.co.uk/'},
 {'Restaurant Name': 'Da Terra',
  'Price Range': '70 - 140 GBP',
  'Restauarant Website': 'https://www.daterra.co.uk/'},
 {'Restaurant Name': 'Restaurant Sat Bains',
  'Price Range': '120 - 155 GBP',
  'Restauarant Website': 'https://www.restaurantsatbains.com/'},
 {'Restaurant Name': 'Raby Hunt',
  'Price Range': '230 - 300 GBP',
  'Restauarant Website': 'https://www.rabyhuntrestaurant.co.uk/'},
 {'Restaurant Name': 'Moor Hall',
  'Price Range': '95 - 195 GBP',
  'Restauarant Website': 'https://www.moorhall.com/'},
 {'Restaurant Name': 'Story',
  'Price Range': '120 - 170 GBP',
  'Restauarant Website': 'https://www.restaurantstory.co.uk/'},
 {'Restaurant Name': 'Andrew Fairlie at Gleneagles',
  'Price Range': '115 - 155 GBP',
  'Restauarant Website': 'https://www.andrewfairlie.co.uk/'},
 {'Restaurant Name': "Le Manoir aux Quat' Saisons, a Belmond Hotel",
  'Price Range': '136 - 194 GBP',
  'Restauarant Website': 'https://www.belmond.com/'},
 {'Restaurant Name': 'Midsummer House',
  'Price Range': '115 - 230 GBP',
  'Restauarant Website': 'www.midsummerhouse.co.uk/'},
 {'Restaurant Name': 'Hand and Flowers',
  'Price Range': '40 - 115 GBP',
  'Restauarant Website': 'https://www.thehandandflowers.co.uk/'},
 {'Restaurant Name': 'Dinner by Heston Blumenthal',
  'Price Range': '87 - 106 GBP',
  'Restauarant Website': 'https://www.dinnerbyheston.com/'},
 {'Restaurant Name': 'A. Wong',
  'Price Range': '48 - 160 GBP',
  'Restauarant Website': 'http://www.awong.co.uk/'},
 {'Restaurant Name': 'Kitchen Table',
  'Price Range': '150 - 195 GBP',
  'Restauarant Website': 'https://www.kitchentablelondon.co.uk/'},
 {'Restaurant Name': 'Claude Bosi at Bibendum',
  'Price Range': '105 - 175 GBP',
  'Restauarant Website': 'https://www.claudebosi.com/'},
 {'Restaurant Name': 'Auberge du Cheval Blanc',
  'Price Range': '82 - 135 EUR',
  'Restauarant Website': 'https://www.au-cheval-blanc.fr/'},
 {'Restaurant Name': "La Table d'Olivier Nasti",
  'Price Range': '165 - 240 EUR',
  'Restauarant Website': 'https://www.lechambard.fr/'},
 {'Restaurant Name': "La Table de l'Alpaga",
  'Price Range': '120 - 180 EUR',
  'Restauarant Website': 'https://www.alpaga.com/'},
 {'Restaurant Name': 'Jean Sulpice',
  'Price Range': '225 - 265 EUR',
  'Restauarant Website': 'https://www.perebise.com/'},
 {'Restaurant Name': 'La Pyramide - Patrick Henriroux',
  'Price Range': '79 - 204 EUR',
  'Restauarant Website': 'https://www.lapyramide.com/'},
 {'Restaurant Name': 'Le Montgomerie',
  'Price Range': '190 - 315 EUR',
  'Restauarant Website': 'https://www.lek2altitude.com/'},
 {'Restaurant Name': 'Serge Vieira',
  'Price Range': '95 - 165 EUR',
  'Restauarant Website': 'https://www.sergevieira.com/'},
 {'Restaurant Name': 'Racine',
  'Price Range': '70 - 195 EUR',
  'Restauarant Website': 'https://www.racine.re/'},
 {'Restaurant Name': 'Sarkara',
  'Price Range': '107 - 135 EUR',
  'Restauarant Website': 'https://www.lek2palace.com/'},
 {'Restaurant Name': 'Au 14 Février',
  'Price Range': '87 - 125 EUR',
  'Restauarant Website': 'https://www.sa-au14fevrier.com/'},
 {'Restaurant Name': "La Côte d'Or",
  'Price Range': '160 - 245 EUR',
  'Restauarant Website': 'https://www.bernard-loiseau.com/'},
 {'Restaurant Name': 'La Maison des Bois - Marc Veyrat',
  'Price Range': '295 - 395 EUR',
  'Restauarant Website': 'https://www.marc-veyrat.fr/'},
 {'Restaurant Name': 'Les Hauts de Loire',
  'Price Range': '89 - 175 EUR',
  'Restauarant Website': 'https://www.hautsdeloire.com/'},
 {'Restaurant Name': 'Alexandre',
  'Price Range': '64 - 215 EUR',
  'Restauarant Website': 'https://www.michelkayser.com/'},
 {'Restaurant Name': 'La Table de Pavie',
  'Price Range': '72 - 215 EUR',
  'Restauarant Website': 'https://www.hostelleriedeplaisance.com/'},
 {'Restaurant Name': 'Le Kintessence',
  'Price Range': '190 - 315 EUR',
  'Restauarant Website': 'https://www.lek2palace.com/'},
 {'Restaurant Name': 'Le Parc Les Crayères',
  'Price Range': '75 - 295 EUR',
  'Restauarant Website': 'www.lescrayeres.com'},
 {'Restaurant Name': 'Maison Rostang',
  'Price Range': '90 - 203 EUR',
  'Restauarant Website': 'https://www.maisonrostang.com/'},
 {'Restaurant Name': 'La Scène',
  'Price Range': '75 - 250 EUR',
  'Restauarant Website': 'https://www.la-scene.paris/'},
 {'Restaurant Name': 'Le Pré - Xavier Beaudiment',
  'Price Range': '39 - 155 EUR',
  'Restauarant Website': 'https://www.restaurant-lepre.com/'},
 {'Restaurant Name': 'La Côte Saint-Jacques',
  'Price Range': '85 - 238 EUR',
  'Restauarant Website': 'https://www.cotesaintjacques.com/'},
 {'Restaurant Name': 'Le Clarence',
  'Price Range': '90 - 320 EUR',
  'Restauarant Website': 'https://www.le-clarence.paris/'},
 {'Restaurant Name': 'La Villa Archange',
  'Price Range': '78 - 350 EUR',
  'Restauarant Website': 'https://www.bruno-oger.com/fr'},
 {'Restaurant Name': 'Paul Bocuse',
  'Price Range': '185 - 285 EUR',
  'Restauarant Website': 'https://www.bocuse.fr/'},
 {'Restaurant Name': 'Le Grand Restaurant - Jean-François Piège',
  'Price Range': '120 - 290 EUR',
  'Restauarant Website': 'http://www.jeanfrancoispiege.com/'},
 {'Restaurant Name': 'Le Neuvième Art',
  'Price Range': '105 - 175 EUR',
  'Restauarant Website': 'https://www.leneuviemeart.com/'},
 {'Restaurant Name': "Le Pressoir d'Argent - Gordon Ramsay",
  'Price Range': '160 - 250 EUR',
  'Restauarant Website': 'https://www.bordeaux.intercontinental.com/'},
 {'Restaurant Name': 'La Marine',
  'Price Range': '130 - 220 EUR',
  'Restauarant Website': 'https://www.alexandrecouillon.com/'},
 {'Restaurant Name': 'Hostellerie Jérôme',
  'Price Range': '110 - 159 EUR',
  'Restauarant Website': 'https://www.hostellerie-jerome.com/'},
 {'Restaurant Name': 'Les Morainières',
  'Price Range': '148 - 220 EUR',
  'Restauarant Website': 'https://www.les-morainieres.com/'},
 {'Restaurant Name': 'Relais de la Poste',
  'Price Range': '60 - 150 EUR',
  'Restauarant Website': 'https://www.relaisposte.com/'},
 {'Restaurant Name': 'Le Taillevent',
  'Price Range': '90 - 245 EUR',
  'Restauarant Website': 'https://www.letaillevent.com/'},
 {'Restaurant Name': "L'Abysse au Pavillon Ledoyen",
  'Price Range': '98 - 280 EUR',
  'Restauarant Website': 'https://www.yannick-alleno.com/'},
 {'Restaurant Name': 'Anne de Bretagne',
  'Price Range': '45 - 165 EUR',
  'Restauarant Website': 'https://www.annedebretagne.com/'},
 {'Restaurant Name': 'David Toutain',
  'Price Range': '100 - 250 EUR',
  'Restauarant Website': 'https://www.davidtoutain.com/'},
 {'Restaurant Name': 'Château de Beaulieu - Christophe Dufossé',
  'Price Range': '90 - 220 EUR',
  'Restauarant Website': 'www.lechateaudebeaulieu.fr'},
 {'Restaurant Name': 'Le Puits St-Jacques',
  'Price Range': '35 - 143 EUR',
  'Restauarant Website': 'https://www.lepuitssaintjacques.fr/'},
 {'Restaurant Name': 'Les Cèdres',
  'Price Range': '110 - 175 EUR',
  'Restauarant Website': 'https://www.restaurantlescedres.fr/'},
 {'Restaurant Name': 'Takao Takano',
  'Price Range': '50 - 150 EUR',
  'Restauarant Website': 'https://www.takaotakano.com/'},
 {'Restaurant Name': 'Villa René Lalique',
  'Price Range': '80 - 205 EUR',
  'Restauarant Website': 'https://www.villarenelalique.com/'},
 {'Restaurant Name': 'Le Meurice Alain Ducasse',
  'Price Range': '250 - 320 EUR',
  'Restauarant Website': 'https://www.alainducasse-meurice.com/fr'},
 {'Restaurant Name': 'Le Chabichou by Stéphane Buron',
  'Price Range': '175 - 320 EUR',
  'Restauarant Website': 'https://www.chabichou-courchevel.com/'},
 {'Restaurant Name': "JY'S",
  'Price Range': '107 - 185 EUR',
  'Restauarant Website': 'https://www.jean-yves-schillinger.com/'},
 {'Restaurant Name': 'La Grenouillère',
  'Price Range': '155 - 215 EUR',
  'Restauarant Website': 'https://www.lagrenouillere.fr/'},
 {'Restaurant Name': 'La Villa Madie',
  'Price Range': '130 - 235 EUR',
  'Restauarant Website': 'https://www.lavillamadie.com/'},
 {'Restaurant Name': 'AUGUST',
  'Price Range': '179 - 210 EUR',
  'Restauarant Website': 'https://www.restaurantaugust.de/'},
 {'Restaurant Name': 'IGNIV by Andreas Caminada',
  'Price Range': '158 - 248 CHF',
  'Restauarant Website': 'https://www.igniv.com/'},
 {'Restaurant Name': 'Memories',
  'Price Range': '195 - 330 CHF',
  'Restauarant Website': 'https://www.memories.ch/'},
 {'Restaurant Name': 'Piccolo Lago',
  'Price Range': '180 EUR',
  'Restauarant Website': 'https://www.piccololago.it/'},
 {'Restaurant Name': '7132 Silver',
  'Price Range': '275 CHF',
  'Restauarant Website': 'https://www.7132silver.com/'},
 {'Restaurant Name': 'Villa Crespi',
  'Price Range': '140 - 190 EUR',
  'Restauarant Website': 'https://www.villacrespi.it/'},
 {'Restaurant Name': 'Ecco',
  'Price Range': '185 - 240 CHF',
  'Restauarant Website': 'https://www.giardino-ascona.ch/'},
 {'Restaurant Name': "Obendorfer's Eisvogel",
  'Price Range': '142 - 190 EUR',
  'Restauarant Website': 'https://www.landhotel-birkenhof.de/'},
 {'Restaurant Name': 'Antica Corona Reale',
  'Price Range': '80 - 130 EUR',
  'Restauarant Website': 'https://www.anticacoronareale.it/'},
 {'Restaurant Name': 'EssZimmer',
  'Price Range': '180 - 275 EUR',
  'Restauarant Website': 'https://www.feinkost-kaefer.de/esszimmer-muenchen'},
 {'Restaurant Name': 'La Madernassa',
  'Price Range': '80 - 300 EUR',
  'Restauarant Website': 'https://www.lamadernassa.it/'},
 {'Restaurant Name': 'Les Deux',
  'Price Range': '185 EUR',
  'Restauarant Website': 'www.lesdeux-muc.de'},
 {'Restaurant Name': 'Alois - Dallmayr Fine Dining',
  'Price Range': '78 - 220 EUR',
  'Restauarant Website': 'https://www.dallmayr.com/alois'},
 {'Restaurant Name': 'Ecco St. Moritz',
  'Price Range': '215 - 270 CHF',
  'Restauarant Website': 'https://www.giardinohotels.ch/'},
 {'Restaurant Name': 'IGNIV by Andreas Caminada',
  'Price Range': '195 - 245 CHF',
  'Restauarant Website': 'https://www.badruttspalace.com/'},
 {'Restaurant Name': 'Da Vittorio',
  'Price Range': '170 - 420 CHF',
  'Restauarant Website': 'https://www.carlton-stmoritz.ch/'},
 {'Restaurant Name': "Cà d'Oro",
  'Price Range': '140 - 190 CHF',
  'Restauarant Website': 'https://www.kempinski.com/stmoritz'},
 {'Restaurant Name': 'La Villa Archange',
  'Price Range': '78 - 350 EUR',
  'Restauarant Website': 'https://www.bruno-oger.com/fr'},
 {'Restaurant Name': 'La Voile - La Réserve Ramatuelle',
  'Price Range': '135 - 210 EUR',
  'Restauarant Website': 'https://www.lareserve-ramatuelle.com/'},
 {'Restaurant Name': "La Palme d'Or",
  'Price Range': '168 - 240 EUR',
  'Restauarant Website': 'www.lapalmedor-restaurant.fr'},
 {'Restaurant Name': "D'O",
  'Price Range': '95 - 165 EUR',
  'Restauarant Website': 'https://www.cucinapop.do/'},
 {'Restaurant Name': 'Flaveur',
  'Price Range': '130 - 200 EUR',
  'Restauarant Website': 'https://www.restaurant-flaveur.com/'},
 {'Restaurant Name': "Luce d'Oro",
  'Price Range': '189 - 229 EUR',
  'Restauarant Website': 'www.schloss-elmau.de'},
 {'Restaurant Name': "La Chèvre d'Or",
  'Price Range': '90 - 260 EUR',
  'Restauarant Website': 'https://www.chevredor.com/'},
 {'Restaurant Name': 'Hostellerie Jérôme',
  'Price Range': '110 - 159 EUR',
  'Restauarant Website': 'https://www.hostellerie-jerome.com/'},
 {'Restaurant Name': 'Il Luogo di Aimo e Nadia',
  'Price Range': '115 - 280 EUR',
  'Restauarant Website': 'https://www.aimoenadia.com/'},
 {'Restaurant Name': 'Seta by Antonio Guida',
  'Price Range': '90 - 230 EUR',
  'Restauarant Website': 'https://www.mandarinoriental.com/'},
 {'Restaurant Name': 'Restaurant Heinz Winkler',
  'Price Range': '96 - 205 EUR',
  'Restauarant Website': 'https://www.residenz-heinz-winkler.de/'},
 {'Restaurant Name': 'Castel finedining',
  'Price Range': '178 - 208 EUR',
  'Restauarant Website': 'https://www.castelfinedining.com'},
 {'Restaurant Name': "Miramonti l'Altro",
  'Price Range': '90 - 150 EUR',
  'Restauarant Website': 'https://www.miramontilaltro.it/'},
 {'Restaurant Name': 'Gourmetstube Einhorn',
  'Price Range': '130 - 165 EUR',
  'Restauarant Website': 'https://www.stafler.com/'},
 {'Restaurant Name': 'Terra',
  'Price Range': '179 EUR',
  'Restauarant Website': 'https://www.terra.place/'},
 {'Restaurant Name': 'Villa Feltrinelli',
  'Price Range': '220 EUR',
  'Restauarant Website': 'https://www.villafeltrinelli.com/'},
 {'Restaurant Name': 'Ikarus',
  'Price Range': '140 - 210 EUR',
  'Restauarant Website': 'https://www.hangar-7.com/'},
 {'Restaurant Name': 'SENNS.Restaurant',
  'Price Range': '85 - 205 EUR',
  'Restauarant Website': 'https://www.senns.restaurant/'},
 {'Restaurant Name': 'Casa Perbellini',
  'Price Range': '65 - 185 EUR',
  'Restauarant Website': 'https://www.casaperbellini.com/'},
 {'Restaurant Name': 'La Peca',
  'Price Range': '95 - 200 EUR',
  'Restauarant Website': 'https://www.lapeca.it/'},
 {'Restaurant Name': 'Il Piccolo Principe',
  'Price Range': '130 - 230 EUR',
  'Restauarant Website': 'https://www.ristoranteilpiccoloprincipe.it/'},
 {'Restaurant Name': 'Antica Osteria Cera',
  'Price Range': '70 - 250 EUR',
  'Restauarant Website': 'https://www.osteriacera.it/'},
 {'Restaurant Name': 'Vrijmoed',
  'Price Range': '69 - 198 EUR',
  'Restauarant Website': 'https://www.vrijmoed.be/'},
 {'Restaurant Name': 'The Jane',
  'Price Range': '215 EUR',
  'Restauarant Website': 'https://www.thejaneantwerp.com/'},
 {'Restaurant Name': 'Ralf Berendsen',
  'Price Range': '95 - 225 EUR',
  'Restauarant Website': 'https://www.restaurantlasource.be/'},
 {'Restaurant Name': 'La Table de Maxime',
  'Price Range': '50 - 109 EUR',
  'Restauarant Website': 'https://www.maximecollard.be/'},
 {'Restaurant Name': 'Comme chez Soi',
  'Price Range': '69 - 355 EUR',
  'Restauarant Website': 'https://www.commechezsoi.be/'},
 {'Restaurant Name': 'Boury',
  'Price Range': '80 - 160 EUR',
  'Restauarant Website': 'https://www.restaurantboury.be/'},
 {'Restaurant Name': 'Slagmolen',
  'Price Range': '60 - 160 EUR',
  'Restauarant Website': 'https://www.slagmolen.be/'},
 {'Restaurant Name': 'Hostellerie St-Nicolas',
  'Price Range': '55 - 155 EUR',
  'Restauarant Website': 'https://www.hostellerie-stnicolas.com/'},
 {'Restaurant Name': 'Castor',
  'Price Range': '45 - 120 EUR',
  'Restauarant Website': 'https://www.cas-tor.be/'},
 {'Restaurant Name': 'Pastorale',
  'Price Range': '65 - 195 EUR',
  'Restauarant Website': 'https://www.depastorale.be/'},
 {'Restaurant Name': 'Château du Mylord',
  'Price Range': '95 - 270 EUR',
  'Restauarant Website': 'https://www.mylord.be/'},
 {'Restaurant Name': 'Cuchara',
  'Price Range': '65 - 205 EUR',
  'Restauarant Website': 'https://www.cuchara.be/'},
 {'Restaurant Name': 'La Paix',
  'Price Range': '105 - 235 EUR',
  'Restauarant Website': 'https://www.lapaix.eu/'},
 {'Restaurant Name': 'Sorn',
  'Price Range': '3,500 THB',
  'Restauarant Website': 'http://www.sornfinesouthern.com/'},
 {'Restaurant Name': "Chef's Table",
  'Price Range': '7,900 THB',
  'Restauarant Website': 'https://www.lebua.com/chefs-table'},
 {'Restaurant Name': 'R-Haan',
  'Price Range': '1,219 - 2,912 THB',
  'Restauarant Website': 'https://www.r-haan.com/'},
 {'Restaurant Name': 'Mezzaluna',
  'Price Range': '6,500 THB',
  'Restauarant Website': 'https://www.lebua.com/mezzaluna'},
 {'Restaurant Name': 'Sühring',
  'Price Range': '3,500 - 5,500 THB',
  'Restauarant Website': 'https://www.restaurantsuhring.com/'},
 {'Restaurant Name': 'Le Normandie',
  'Price Range': '3,200 - 8,200 THB',
  'Restauarant Website': 'https://www.mandarinoriental.com/bangkok'},
 {'Restaurant Name': 'Casa de Chá da Boa Nova',
  'Price Range': '70 - 195 EUR',
  'Restauarant Website': 'www.casadechadaboanova.pt'},
 {'Restaurant Name': 'Ocean',
  'Price Range': '210 EUR',
  'Restauarant Website': 'www.restauranteocean.com'},
 {'Restaurant Name': 'The Yeatman',
  'Price Range': '180 EUR',
  'Restauarant Website': 'www.the-yeatman-hotel.com'},
 {'Restaurant Name': 'Belcanto',
  'Price Range': '125 - 195 EUR',
  'Restauarant Website': 'www.belcanto.pt'},
 {'Restaurant Name': "Il Gallo d'Oro",
  'Price Range': '130 - 200 EUR',
  'Restauarant Website': 'www.ilgallodoro.com'},
 {'Restaurant Name': 'Vila Joya',
  'Price Range': '110 - 195 EUR',
  'Restauarant Website': 'www.vilajoya.com/'},
 {'Restaurant Name': 'Alma',
  'Price Range': '83 - 145 EUR',
  'Restauarant Website': 'www.almalisboa.pt'},
 {'Restaurant Name': 'Disfrutar',
  'Price Range': '165 - 210 EUR',
  'Restauarant Website': 'www.disfrutarbarcelona.com'},
 {'Restaurant Name': 'Ramón Freixa Madrid',
  'Price Range': '90 - 165 EUR',
  'Restauarant Website': 'www.ramonfreixamadrid.com'},
 {'Restaurant Name': 'Cinc Sentits',
  'Price Range': '119 - 139 EUR',
  'Restauarant Website': 'www.cincsentits.com'},
 {'Restaurant Name': 'Noor',
  'Price Range': '95 - 190 EUR',
  'Restauarant Website': 'www.noorrestaurant.es'},
 {'Restaurant Name': 'El Molino de Urdániz',
  'Price Range': '120 - 140 EUR',
  'Restauarant Website': 'www.elmolinourdaniz.com'},
 {'Restaurant Name': 'Cabaña Buenavista',
  'Price Range': '70 - 140 EUR',
  'Restauarant Website': 'www.cabanabuenavista.com'},
 {'Restaurant Name': 'M.B',
  'Price Range': '105 - 165 EUR',
  'Restauarant Website': 'www.ritzcarlton.com'},
 {'Restaurant Name': 'Coque',
  'Price Range': '198 - 230 EUR',
  'Restauarant Website': 'www.restaurantecoque.com'},
 {'Restaurant Name': 'Casa Marcial',
  'Price Range': '70 - 180 EUR',
  'Restauarant Website': 'www.casamarcial.com'},
 {'Restaurant Name': 'Ricard Camarena',
  'Price Range': '135 - 175 EUR',
  'Restauarant Website': 'www.ricardcamarenarestaurant.com'},
 {'Restaurant Name': 'Moments',
  'Price Range': '130 - 189 EUR',
  'Restauarant Website': 'www.mandarinoriental.es'},
 {'Restaurant Name': 'Atrio',
  'Price Range': '185 EUR',
  'Restauarant Website': 'www.restauranteatrio.com'},
 {'Restaurant Name': 'Maralba',
  'Price Range': '65 - 99 EUR',
  'Restauarant Website': 'www.maralbarestaurante.es'},
 {'Restaurant Name': 'BonAmb',
  'Price Range': '90 - 160 EUR',
  'Restauarant Website': 'www.bonamb.com'},
 {'Restaurant Name': 'Les Cols',
  'Price Range': '155 EUR',
  'Restauarant Website': 'www.lescols.com'},
 {'Restaurant Name': 'Miramar',
  'Price Range': '125 - 195 EUR',
  'Restauarant Website': 'www.restaurantmiramar.com'},
 {'Restaurant Name': 'Enoteca Paco Pérez',
  'Price Range': '175 EUR',
  'Restauarant Website': 'www.enotecapacoperez.com'},
 {'Restaurant Name': "L'Escaleta",
  'Price Range': '60 - 135 EUR',
  'Restauarant Website': 'www.lescaleta.com'},
 {'Restaurant Name': 'Mugaritz',
  'Price Range': '231 EUR',
  'Restauarant Website': 'www.mugaritz.com'},
 {'Restaurant Name': 'Skina',
  'Price Range': '165 - 189 EUR',
  'Restauarant Website': 'www.restauranteskina.com'},
 {'Restaurant Name': 'Culler de Pau',
  'Price Range': '95 - 150 EUR',
  'Restauarant Website': 'www.cullerdepau.com'},
 {'Restaurant Name': 'Bo.TiC',
  'Price Range': '95 - 180 EUR',
  'Restauarant Website': 'www.bo-tic.com'},
 {'Restaurant Name': 'Cocina Hermanos Torres',
  'Price Range': '42 - 195 EUR',
  'Restauarant Website': 'www.cocinahermanostorres.com'},
 {'Restaurant Name': 'Bardal',
  'Price Range': '150 - 170 EUR',
  'Restauarant Website': 'www.restaurantebardal.com'},
 {'Restaurant Name': 'El Portal de Echaurren',
  'Price Range': '150 - 165 EUR',
  'Restauarant Website': 'www.echaurren.com'},
 {'Restaurant Name': 'DSTAgE',
  'Price Range': '145 - 170 EUR',
  'Restauarant Website': 'www.dstageconcept.com'},
 {'Restaurant Name': 'Paco Roncero',
  'Price Range': '85 - 148 EUR',
  'Restauarant Website': 'www.pacoroncerorestaurante.com'},
 {'Restaurant Name': 'Angle',
  'Price Range': '145 - 160 EUR',
  'Restauarant Website': 'www.anglebarcelona.com'},
 {'Restaurant Name': 'El Poblet',
  'Price Range': '98 - 135 EUR',
  'Restauarant Website': 'www.elpobletrestaurante.com'},
 {'Restaurant Name': 'BEIGE Alain Ducasse',
  'Price Range': '12,000 - 30,000 JPY',
  'Restauarant Website': 'http://beige-tokyo.com/'},
 {'Restaurant Name': 'Sushi Kanesaka',
  'Price Range': '19,000 - 37,000 JPY',
  'Restauarant Website': 'http://www.sushi-kanesaka.com/'},
 {'Restaurant Name': 'Jingumae Higuchi',
  'Price Range': '31,000 - 37,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Jushu',
  'Price Range': '19,000 - 25,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Daigo',
  'Price Range': '16,000 - 25,000 JPY',
  'Restauarant Website': 'http://www.atago-daigo.jp/'},
 {'Restaurant Name': 'Florilège',
  'Price Range': '9,500 - 19,000 JPY',
  'Restauarant Website': 'https://www.aoyama-florilege.jp/'},
 {'Restaurant Name': 'Jingumae Higuchi',
  'Price Range': '31,000 - 37,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': "L'ATELIER de Joël Robuchon",
  'Price Range': '4,000 - 22,000 JPY',
  'Restauarant Website': 'https://www.robuchon.jp/'},
 {'Restaurant Name': 'Azabu Yukimura',
  'Price Range': '43,000 - 49,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Sukiyabashi Jiro Roppongiten',
  'Price Range': '25,000 - 39,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Jushu',
  'Price Range': '19,000 - 25,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'PRISMA',
  'Price Range': '19,000 - 21,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Usukifugu Yamadaya',
  'Price Range': '29,000 - 41,000 JPY',
  'Restauarant Website': 'https://www.usukifugu-yamadaya.jp/'},
 {'Restaurant Name': 'Seizan',
  'Price Range': '18,000 - 50,000 JPY',
  'Restauarant Website': 'https://seizan-mita.com/'},
 {'Restaurant Name': 'Seisoka',
  'Price Range': '8,500 - 43,000 JPY',
  'Restauarant Website': 'https://seisoka.com/'},
 {'Restaurant Name': 'Tentempura Uchitsu',
  'Price Range': '31,000 JPY',
  'Restauarant Website': 'http://tempura-uchitsu.com/'},
 {'Restaurant Name': 'Tempura Ginya',
  'Price Range': '21,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'LA TABLE de Joël Robuchon',
  'Price Range': '6,500 - 21,000 JPY',
  'Restauarant Website': 'https://www.robuchon.jp/'},
 {'Restaurant Name': 'Sushi Kimura',
  'Price Range': '26,000 - 33,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Miyamaso',
  'Price Range': '19,000 - 32,000 JPY',
  'Restauarant Website': 'http://miyamasou.jp/'},
 {'Restaurant Name': 'Sojiki Nakahigashi',
  'Price Range': '9,000 - 26,000 JPY',
  'Restauarant Website': 'https://www.soujiki-nakahigashi.co.jp/'},
 {'Restaurant Name': 'Kyokaiseki Kichisen',
  'Price Range': '15,000 - 39,000 JPY',
  'Restauarant Website': 'https://www.kichisen-kyoto.com/'},
 {'Restaurant Name': 'Otagi',
  'Price Range': '22,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Yusokuryori Mankamero',
  'Price Range': '13,000 - 38,000 JPY',
  'Restauarant Website': 'http://www.mankamerou.com/'},
 {'Restaurant Name': 'Shimmonzen Yonemura',
  'Price Range': '10,000 - 21,000 JPY',
  'Restauarant Website': 'https://r-yonemura.jp/'},
 {'Restaurant Name': 'Kappo Chihiro',
  'Price Range': '19,000 - 27,000 JPY',
  'Restauarant Website': 'http://www.kyotochihiro.com/'},
 {'Restaurant Name': 'Oryori Mitsuyasu',
  'Price Range': '20,000 JPY',
  'Restauarant Website': 'http://kyoto-mitsuyasu.com/'},
 {'Restaurant Name': 'Kodaiji Wakuden',
  'Price Range': '28,000 - 50,000 JPY',
  'Restauarant Website': 'https://www.wakuden.jp/'},
 {'Restaurant Name': 'Gion Maruyama',
  'Price Range': '11,000 - 64,000 JPY',
  'Restauarant Website': 'https://gionmaruyama.com/'},
 {'Restaurant Name': 'Gion Matayoshi',
  'Price Range': '12,000 - 37,000 JPY',
  'Restauarant Website': 'http://www.gion-matayoshi.com/'},
 {'Restaurant Name': 'Kyotenjin Noguchi',
  'Price Range': '30,000 - 35,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Sumibi Kappo Ifuki',
  'Price Range': '24,000 - 35,000 JPY',
  'Restauarant Website': 'https://gion-ifuki.com/'},
 {'Restaurant Name': 'Gion Owatari',
  'Price Range': '32,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Gion Nishikawa',
  'Price Range': '6,500 - 31,000 JPY',
  'Restauarant Website': 'http://r.goope.jp/gion-nishikawa/'},
 {'Restaurant Name': 'Kikunoi Roan',
  'Price Range': '9,000 - 32,000 JPY',
  'Restauarant Website': 'https://kikunoi.jp/'},
 {'Restaurant Name': 'Kenninji Gion Maruyama',
  'Price Range': '11,000 - 64,000 JPY',
  'Restauarant Website': 'https://gionmaruyama.com/'},
 {'Restaurant Name': 'Ogata',
  'Price Range': '50,000 - 60,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Wagokoro Izumi',
  'Price Range': '7,000 - 29,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Shunsaiten Tsuchiya',
  'Price Range': '8,000 - 24,000 JPY',
  'Restauarant Website': 'http://www.shunsaiten-tsuchiya.com/'},
 {'Restaurant Name': 'Tenjimbashi Aoki',
  'Price Range': '22,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Sushiyoshi',
  'Price Range': '25,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Miyamoto',
  'Price Range': '19,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'KAHALA',
  'Price Range': '31,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Numata',
  'Price Range': '22,000 JPY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Koryu',
  'Price Range': '33,000 JPY',
  'Restauarant Website': 'https://www.koryu.net/'},
 {'Restaurant Name': 'La Peca',
  'Price Range': '95 - 200 EUR',
  'Restauarant Website': 'https://www.lapeca.it/'},
 {'Restaurant Name': 'Quattro Passi',
  'Price Range': '75 - 200 EUR',
  'Restauarant Website': 'http://www.ristorantequattropassi.com/'},
 {'Restaurant Name': 'La Madia',
  'Price Range': '90 - 170 EUR',
  'Restauarant Website': 'http://www.ristorantelamadia.it'},
 {'Restaurant Name': 'La Trota',
  'Price Range': '90 - 130 EUR',
  'Restauarant Website': 'https://www.latrota.com/'},
 {'Restaurant Name': 'Villa Crespi',
  'Price Range': '140 - 190 EUR',
  'Restauarant Website': 'https://www.villacrespi.it/'},
 {'Restaurant Name': 'Taverna Estia',
  'Price Range': '95 - 180 EUR',
  'Restauarant Website': 'https://www.tavernaestia.it/'},
 {'Restaurant Name': 'Caino',
  'Price Range': '115 - 190 EUR',
  'Restauarant Website': 'http://www.dacaino.it/'},
 {'Restaurant Name': 'Il Piccolo Principe',
  'Price Range': '130 - 230 EUR',
  'Restauarant Website': 'https://www.ristoranteilpiccoloprincipe.it/'},
 {'Restaurant Name': 'Antica Osteria Cera',
  'Price Range': '70 - 250 EUR',
  'Restauarant Website': 'https://www.osteriacera.it/'},
 {'Restaurant Name': 'Duomo',
  'Price Range': '65 - 190 EUR',
  'Restauarant Website': 'https://www.cicciosultano.it/'},
 {'Restaurant Name': "L'Olivo",
  'Price Range': '125 - 210 EUR',
  'Restauarant Website': 'https://www.capripalace.com/'},
 {'Restaurant Name': 'Casa Perbellini',
  'Price Range': '65 - 185 EUR',
  'Restauarant Website': 'https://www.casaperbellini.com/'},
 {'Restaurant Name': 'Don Alfonso 1890',
  'Price Range': '120 - 190 EUR',
  'Restauarant Website': 'https://www.donalfonso.com/'},
 {'Restaurant Name': 'Glam Enrico Bartolini',
  'Price Range': '130 - 230 EUR',
  'Restauarant Website': 'http://www.ristoranteglam.com'},
 {'Restaurant Name': "Harry's Piccolo",
  'Price Range': '100 - 200 EUR',
  'Restauarant Website': 'https://www.harrystrieste.it/'},
 {'Restaurant Name': 'Arnolfo',
  'Price Range': '120 - 160 EUR',
  'Restauarant Website': 'https://www.arnolfo.com/'},
 {'Restaurant Name': 'La Madernassa',
  'Price Range': '80 - 300 EUR',
  'Restauarant Website': 'https://www.lamadernassa.it/'},
 {'Restaurant Name': "Miramonti l'Altro",
  'Price Range': '90 - 150 EUR',
  'Restauarant Website': 'https://www.miramontilaltro.it/'},
 {'Restaurant Name': 'Antica Corona Reale',
  'Price Range': '80 - 130 EUR',
  'Restauarant Website': 'https://www.anticacoronareale.it/'},
 {'Restaurant Name': "D'O",
  'Price Range': '95 - 165 EUR',
  'Restauarant Website': 'https://www.cucinapop.do/'},
 {'Restaurant Name': 'Villa Feltrinelli',
  'Price Range': '220 EUR',
  'Restauarant Website': 'https://www.villafeltrinelli.com/'},
 {'Restaurant Name': 'Bracali',
  'Price Range': '135 - 225 EUR',
  'Restauarant Website': 'https://www.mondobracali.it/'},
 {'Restaurant Name': 'Santa Elisabetta',
  'Price Range': '74 - 199 EUR',
  'Restauarant Website': 'https://www.ristorantesantaelisabetta.it/'},
 {'Restaurant Name': 'Torre del Saracino',
  'Price Range': '105 - 220 EUR',
  'Restauarant Website': 'https://www.torredelsaracino.it/'},
 {'Restaurant Name': 'Magnolia',
  'Price Range': '95 - 140 EUR',
  'Restauarant Website': 'https://www.magnoliaristorante.it/'},
 {'Restaurant Name': 'Piccolo Lago',
  'Price Range': '180 EUR',
  'Restauarant Website': 'https://www.piccololago.it/'},
 {'Restaurant Name': 'Il Luogo di Aimo e Nadia',
  'Price Range': '115 - 280 EUR',
  'Restauarant Website': 'https://www.aimoenadia.com/'},
 {'Restaurant Name': 'Gourmetstube Einhorn',
  'Price Range': '130 - 165 EUR',
  'Restauarant Website': 'https://www.stafler.com/'},
 {'Restaurant Name': 'Il Pagliaccio',
  'Price Range': '85 - 185 EUR',
  'Restauarant Website': 'https://www.ristoranteilpagliaccio.com/'},
 {'Restaurant Name': 'San Domenico',
  'Price Range': '60 - 180 EUR',
  'Restauarant Website': 'https://www.sandomenico.it/'},
 {'Restaurant Name': 'Seta by Antonio Guida',
  'Price Range': '90 - 230 EUR',
  'Restauarant Website': 'https://www.mandarinoriental.com/'},
 {'Restaurant Name': 'Madonnina del Pescatore',
  'Price Range': '65 - 175 EUR',
  'Restauarant Website': 'https://www.morenocedroni.it/'},
 {'Restaurant Name': 'Kojima',
  'Price Range': '200,000 - 380,000 KRW',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': "L'Impression",
  'Price Range': '100,000 - 220,000 KRW',
  'Restauarant Website': 'http://www.limpression.co.kr/'},
 {'Restaurant Name': 'alla Prima',
  'Price Range': '77,000 - 200,000 KRW',
  'Restauarant Website': 'https://www.allaprima.co.kr/'},
 {'Restaurant Name': 'Jungsik',
  'Price Range': '78,000 - 230,000 KRW',
  'Restauarant Website': 'https://www.jungsik.kr/'},
 {'Restaurant Name': 'Mosu',
  'Price Range': '140,000 - 270,000 KRW',
  'Restauarant Website': 'http://mosuseoul.com'},
 {'Restaurant Name': 'Kwonsooksoo',
  'Price Range': '105,000 - 240,000 KRW',
  'Restauarant Website': 'https://www.kwonsooksoo.com/'},
 {'Restaurant Name': 'Mingles',
  'Price Range': '120,000 - 220,000 KRW',
  'Restauarant Website': 'http://www.restaurant-mingles.com/'},
 {'Restaurant Name': 'Shanghai Cuisine',
  'Price Range': '300 - 1,000 CNY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Jingji',
  'Price Range': '300 - 2,000 CNY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Taian Table',
  'Price Range': '1,858 - 2,188 CNY',
  'Restauarant Website': 'https://taian-table.cn/'},
 {'Restaurant Name': 'Ji Pin Court',
  'Price Range': '200 - 1,000 CNY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Da Vittorio',
  'Price Range': '688 - 2,888 CNY',
  'Restauarant Website': 'https://www.davittorio.com/'},
 {'Restaurant Name': "L'Atelier de Joël Robuchon",
  'Price Range': '600 - 1,798 CNY',
  'Restauarant Website': 'http://www.joelrobuchon-china.com/'},
 {'Restaurant Name': '8 ½ Otto e Mezzo Bombana',
  'Price Range': '698 - 2,380 CNY',
  'Restauarant Website': 'https://www.ottoemezzobombana.com/'},
 {'Restaurant Name': 'Imperial Treasure Fine Chinese Cuisine (Huangpu)',
  'Price Range': '200 - 1,000 CNY',
  'Restauarant Website': 'https://www.imperialtreasure.com/'},
 {'Restaurant Name': 'Canton 8 (Runan Street)',
  'Price Range': '100 - 500 CNY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Bao Li Xuan',
  'Price Range': '300 - 1,288 CNY',
  'Restauarant Website': 'https://www.bulgarihotels.com/shanghai'},
 {'Restaurant Name': 'YongFoo Élite',
  'Price Range': '400 - 1,000 CNY',
  'Restauarant Website': 'N/A'},
 {'Restaurant Name': 'Xin Rong Ji (Nanyang Road)',
  'Price Range': '1,000 - 2,500 CNY',
  'Restauarant Website': 'www.xinrongji.cc'},
 {'Restaurant Name': 'D.O.M.',
  'Price Range': '415 - 700 BRL',
  'Restauarant Website': 'http://www.domrestaurante.com.br/'},
 {'Restaurant Name': 'Ryo Gastronomia',
  'Price Range': '160 - 650 BRL',
  'Restauarant Website': 'https://www.ryogastronomia.com.br/'},
 {'Restaurant Name': 'Oteque',
  'Price Range': '440 BRL',
  'Restauarant Website': 'https://www.oteque.com/'},
 {'Restaurant Name': 'Oro',
  'Price Range': '445 - 555 BRL',
  'Restauarant Website': 'http://www.ororestaurante.com.br/'},
 {'Restaurant Name': 'Spondi',
  'Price Range': '120 - 165 EUR',
  'Restauarant Website': 'https://www.spondi.gr/'},
 {'Restaurant Name': 'Silvio Nickol Gourmet Restaurant',
  'Price Range': '23 - 165 EUR',
  'Restauarant Website': 'https://www.palais-coburg.com/'},
 {'Restaurant Name': 'Steirereck im Stadtpark',
  'Price Range': '74 - 169 EUR',
  'Restauarant Website': 'https://www.steirereck.at/'},
 {'Restaurant Name': 'Mraz & Sohn',
  'Price Range': '145 EUR',
  'Restauarant Website': 'https://www.mrazundsohn.at/'},
 {'Restaurant Name': 'Konstantin Filippou',
  'Price Range': '56 - 189 EUR',
  'Restauarant Website': 'https://www.konstantinfilippou.com/'},
 {'Restaurant Name': 'SENNS.Restaurant',
  'Price Range': '85 - 205 EUR',
  'Restauarant Website': 'https://www.senns.restaurant/'},
 {'Restaurant Name': 'Ikarus',
  'Price Range': '140 - 210 EUR',
  'Restauarant Website': 'https://www.hangar-7.com/'}]